FL-11 Display The Task List Dinamically
kincsokiss/FamiList pull request #10
Opened 2023-06-15 14:55 UTC by lkcshna

2023-06-15 18:37 UTC, csongormarton commented on src/views/TaskItem.vue
> +      //const task = props.taskItem;
Kommentelt kodreszt nem szabad a kodba hagyni.

2023-06-15 18:38 UTC, csongormarton commented on src/views/TaskItem.vue
> +      console.log(props.taskItem)
console.log-ot nem szabad a kodba hagyni. Csak tesztelesre hasznaljuk

2023-06-19 13:08 UTC, kincsokiss requested changes

2023-06-19 13:08 UTC, kincsokiss commented on src/views/ToDoList.vue
> +  // az ion-listre kell a v-for, a taskitemnek atadni egy elemet, propot hogy adunkk at
If this comment is not needed anymore, please remove it.

2023-06-19 13:08 UTC, kincsokiss commented on src/views/ToDoList.vue
> +  console.log(taskItem);
Please add descriptive console message or remove it.
Ex. console.log('Tas item: ', taskItem);

2023-06-19 15:47 UTC, closed without merging